spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true

server:
  error:
    include-message: always
    whitelabel:
      enabled: false
    include-exception: false
#logging.level:
#  root: DEBUG
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
#  org.hibernate.orm.jdbc.bind: trace
